language: ruby

services:
  - docker

before_install:
  - docker-compose -v
  - docker-compose up

script:
  - docker run --network=host -v /etc/properties/gateway-client/application.properties:/etc/hercules vstk/hercules-gateway-client:0.38.0-SNAPSHOT
