version: '2'

services:
  #------------------------------------------ Tracing
  # Cassandra
  cassandra:
    image: cassandra
    container_name: cassandra
    ports:
      - 9042:9042
    environment:
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 512M

  #------------------------------------------- Metrics
  # Graphite + Carbon - metric DB and receiver
  graphite:
    image: nickstenning/graphite
    container_name: graphite
    ports:
      - 8080:80
      - 2003:2003

  # Grafana - metric visualization
  grafana:
    image: grafana/grafana:4.5.2
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_METRICS_GRAPHITE_ADDRESS: "graphite:2003"

  #------------------------------------------- Logs
  # Elasticsearch - log DB
  elasticsearch:
    image: elasticsearch:latest
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - 9200:9200

  # Kibana - log vizualizer
  kibana:
    image: kibana:latest
    container_name: kibana
    restart: "unless-stopped"
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      NODE_OPTIONS: "--max-old-space-size=300"

  #-------------------------------------------- Queue
  # Zookeeper - KV storage for Kafka
  zookeeper:
    image: zookeeper:latest
    restart: always
    container_name: zk
    ports:
      - 2181:2181
    environment:
      - ZOO_MY_ID=1

  # Kafka - stream processing engine
  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_HEAP_OPTS: "-Xmx512m -Xms512m"
  #---------------------------------------------- Services
  # Airlock Gate - HTTP -> Kafka proxy
  gate:
    image: skbkontur/airlock.gate:latest
    ports:
      - 8888:8888
    depends_on:
      - kafka
    volumes:
      - ./etc/airlock-gate:/etc/vostok/airlock-gate
    entrypoint: ["/bin/wait-for-it.sh", "kafka:9092", "--timeout=30", "--strict", "--", "java", "-Xms256m", "-Xmx256m", "-XX:+UseG1GC", "-XX:MaxGCPauseMillis=200", "-jar","target/vostok-airlock-gate-1.0-SNAPSHOT.jar"]

  # Log consumer
  logs:
    image: skbkontur/airlock.consumer:latest
    depends_on:
      - kafka
      - graphite
      - elasticsearch
    entrypoint: ["/bin/wait-for-it.sh", "elasticsearch:9200", "--timeout=30", "--strict", "--", "dotnet", "/app/Vostok.AirlockConsumer.Logs/out/Vostok.AirlockConsumer.Logs.dll"]

  # Metrics consumer
  metrics:
    image: skbkontur/airlock.consumer:latest
    depends_on:
      - kafka
      - graphite
    entrypoint: ["/bin/wait-for-it.sh", "graphite:2003", "--timeout=30", "--strict", "--", "dotnet", "/app/Vostok.AirlockConsumer.Metrics/out/Vostok.AirlockConsumer.Metrics.dll"]

  # Metrics aggregation consumer
  metrics_aggr:
    image: skbkontur/airlock.consumer:latest
    depends_on:
      - kafka
      - gate
      - graphite
    entrypoint: ["/bin/wait-for-it.sh", "gate:8888", "--timeout=30", "--strict", "--", "dotnet", "/app/Vostok.AirlockConsumer.MetricsAggregator/out/Vostok.AirlockConsumer.MetricsAggregator.dll"]

  # Tracing consumer
  tracing:
    image: skbkontur/airlock.consumer:latest
    depends_on:
      - kafka
      - graphite
      - cassandra
    entrypoint: ["/bin/wait-for-it.sh", "cassandra:9042", "--timeout=30", "--strict", "--", "dotnet", "/app/Vostok.AirlockConsumer.Tracing/out/Vostok.AirlockConsumer.Tracing.dll"]

  # TracesToEvents consumer
  tte:
    image: skbkontur/airlock.consumer:latest
    depends_on:
      - kafka
      - graphite
      - gate
    entrypoint: ["/bin/wait-for-it.sh", "gate:8888", "--timeout=30", "--strict", "--", "dotnet", "/app/Vostok.AirlockConsumer.TracesToEvents/out/Vostok.AirlockConsumer.TracesToEvents.dll"]

  contrails_api:
    image: skbkontur/contrails.api:latest
    container_name: contrails_api
    depends_on:
      - cassandra
    ports:
      - 8084:10623

  contrails_web:
    image: skbkontur/contrails.web:latest
    depends_on:
      - contrails_api
    ports:
      - 80:80
