airlock.consumer.log.file.pattern: "./log/actions-{Date}.txt"
airlock.consumer.elastic.endpoints:
 - 'http://elasticsearch:9200/'

# kafka consumer settings
bootstrap.servers: "kafka:9092"
client.id: "integration_test"
group.id: airlock

# kafka consumer settings
cassandra.keyspace: airlock
cassandra.spans.tablename: spans
cassandra.endpoints:
  - 'cassandra:9042'
airlock.apikey: UniversalApiKey
airlock.endpoints:
  - "http://gate:8888/"

airlock.consumer.graphite.host: graphite
airlock.consumer.graphite.port: 2003
airlock.metricsAggregator.pastGap: "00:00:20"
airlock.metricsAggregator.futureGap: "01:00:00"
airlock.metricsAggregator.startGap: "00:10:00"
cassandra.max.threads: 1000
cassandra.save.retry.max.attempts: 10
cassandra.save.retry.min.delay: 10
cassandra.save.retry.max.delay: 1000
